Ignore PropertyNotSetInConstructor, it's unused in the class and marked `@internal` in parent
> ERROR: PropertyNotSetInConstructor - app/Form/UiForm.php:11:7 - Property MichalSpacekCz\Form\UiForm::$httpRequest is not defined in constructor of MichalSpacekCz\Form\UiForm or in any methods called in the constructor (see https://psalm.dev/074)
class UiForm extends Form