Change where cache is queried/stored into, so we can pass expected params ($item, $save) to the callback
Those params are not really used/useful, both expires at null and save = true are the default anyway, but Psalm would like me to declare them in the callback so let's also use them, even seemingly only.

Resolve
```
ERROR: PossiblyInvalidArgument - app/Formatter/TexyFormatter.php:197:62 - Argument 2 of Symfony\Contracts\Cache\CacheInterface::get expects Symfony\Contracts\Cache\CallbackInterface<string>|callable(Psr\Cache\CacheItemInterface, bool):string|callable(Symfony\Contracts\Cache\ItemInterface, bool):string, but possibly different type callable():string provided (see https://psalm.dev/092)
                        $formatted = $this->cache->get($this->getCacheKey($text), $callback);
```