"Downgrade" non-empty-list to just list because Psalm complains about adding to it or something
Not sure why but compare https://psalm.dev/r/410933b174 and https://phpstan.org/r/9fd63a49-7e56-4116-b70b-783fddd35566

Resolves
```
ERROR: InvalidPropertyAssignmentValue - app/Makefile/Makefile.php:48:6 - $this->targetDefinitions with declared type 'array<string, non-empty-list<int>>' cannot be assigned type 'non-empty-array<non-falsy-string, list{0?: int, ...<int>}>' (see https://psalm.dev/145)
                                        $this->targetDefinitions[$target][] = $index + 1;
```