Always set an Algorithm when creating a site so the $algorithms array can be marked non-empty-array
Resolves
```
ERROR: PossiblyNullArrayOffset - app/Pulse/WildcardSite.php:68:10 - Cannot access value on variable $this->algorithms using possibly null offset null|string (see https://psalm.dev/125)
                return $this->algorithms[array_key_first($this->algorithms)];
```