Return an object from OpenSsl::x509parse() because Psalm sees some more fields in the array
Resolve
```
ERROR: InvalidReturnType - app/Tls/OpenSsl.php:15:13 - The declared return type 'array{serialNumberHex: string, subject: array{commonName: string}, validFrom_time_t: int, validTo_time_t: int}' for MichalSpacekCz\Tls\OpenSsl::x509parse is incorrect, got 'array{serialNumberHex: string, subject: array{commonName: string, ...<array-key, mixed>}, validFrom_time_t: int, validTo_time_t: int, ...<array-key, mixed>}' (see https://psalm.dev/011)
         * @return array{subject:array{commonName:string}, validFrom_time_t:int, validTo_time_t:int, serialNumberHex:string}

ERROR: InvalidReturnStatement - app/Tls/OpenSsl.php:34:10 - The inferred type 'array{serialNumberHex: string, subject: array{commonName: string, ...<array-key, mixed>}, validFrom_time_t: int, validTo_time_t: int, ...<array-key, mixed>}' does not match the declared return type 'array{serialNumberHex: string, subject: array{commonName: string}, validFrom_time_t: int, validTo_time_t: int}' for MichalSpacekCz\Tls\OpenSsl::x509parse (see https://psalm.dev/128)
                return $info;
```