Make sure $slideNumber is always defined
Well, it would be, there's no way the exception would be thrown on the lines preceding where the variable is defined, but here we are. I think PHPStan also had the same problem earlier, but has been fixed since then. Psalm's not there yet.

Resolves:
```
ERROR: PossiblyUndefinedVariable - app/Talks/TalkSlides.php:259:39 - Possibly undefined variable $slideNumber, first seen on line 241 (see https://psalm.dev/018)
                        throw new DuplicatedSlideException($slideNumber, previous: $e);
```