Add metadata as array to the Route, not string
If not, Psalm then says the following but I have no idea why, the class method listed in the error doesn't expect what Psalm says it expects, the interface does, but that's not listed here:

> ERROR: InvalidArgument - app/EasterEgg/NetteCve202015227.php:84:62 - Argument 2 of Nette\Application\Routers\RouteList::addRoute expects array<array-key, mixed>, but 'Nette:micro' provided (see https://psalm.dev/004)
                $router->withModule('EasterEgg')->addRoute('/nette.micro', 'Nette:micro');

I have also moved the code to the EasterEgg namespace so it's all together, and added a test.